swagger: '2.0'
info:
  title: comant API
  version: "1.0.0"

schemes:
  - http
  - https

basePath: /api/v1
produces:
  - application/json

paths:
  /login:
    get:
      summary: Authenticates user
      description: |
        Returns a JWT token that can be used for accessing protected API
        methods.
      parameters:
      - name: username
        in: query
        description: Username
        required: true
        type: string
      - name: password
        in: query
        description: Password
        required: true
        type: string
      responses:
        200:
          description: Authentication token
          schema:
            type: string
            format: JWT token
        403:
          description: Bad credentials

  /user/{username}:
    get:
      summary: Returns basic user info
      description: |
        Returns basic info about user.
      parameters:
      - name: username
        in: path
        description: Username of target user
        required: true
        type: string
      responses:
        200:
          description: Basic user info
          schema:
            $ref: '#/definitions/User'

  /user/{username}/instructedCourses/:
    get:
      summary: Returns courses instructed by target user
      description: |
        Return an array of courses instructed by target user.
      parameters:
      - name: username
        in: path
        description: Username of target user
        required: true
        type: string
      responses:
        200:
          description: Courses array
          schema:
            type: array
            items:
              $ref: '#/definitions/Course'

  /user/{username}/listenedCourses/:
    get:
      summary: Returns courses listened by target user
      description: |
        Return an array of courses listened by target user.
      parameters:
      - name: username
        in: path
        description: Username of target user
        required: true
        type: string
      responses:
        200:
          description: Courses array
          schema:
            type: array
            items:
              $ref: '#/definitions/Course'

  /course/{id}:
    get:
      summary: Returns basic course info
      description: |
        Returns basic info about course.
      parameters:
      - name: id
        in: path
        description: Id of target course
        required: true
        type: integer
        format: int32
      responses:
        200:
          description: Basic course info
          schema:
            $ref: '#/definitions/Course'

  /course/{id}/instructors/:
    get:
      summary: Returns users instructing target course
      description: |
        Return an array of users instructing target course.
      parameters:
      - name: id
        in: path
        description: Id of target course
        required: true
        type: integer
        format: int32
      responses:
        200:
          description: Users array
          schema:
            type: array
            items:
              $ref: '#/definitions/User'

  /course/{id}/listeners/:
    get:
      summary: Returns users listening to target course
      description: |
        Return an array of users listening to target course.
      parameters:
      - name: id
        in: path
        description: Id of target course
        required: true
        type: integer
        format: int32
      responses:
        200:
          description: Users array
          schema:
            type: array
            items:
              $ref: '#/definitions/User'

definitions:
  User:
    type: object
    properties:
      username:
        type: string
        description: Username
      firstname:
        type: string
        description: User first name
      lastname:
        type: string
        description: User last name
      role:
        type: string
        description: User role
        enum:
        - Student
        - Teacher
        - Admin

  Course:
    type: object
    properties:
      name:
        type: string
        description: Course name
      description:
        type: string
        description: Course description
      startsOn:
        type: string
        format: date
        description: Course start date
      endsOn:
        type: string
        format: date
        description: Course end date